version: "3.7"
services:
  actix:
    build:
      context: .
      target: build  
    platform: linux/amd64
    ports:
      - "8808:8808"
    depends_on:
      - db
    networks:
      - app
    tty: true
    user: root
    environment:
      RUST_BACKTRACE: full
    volumes:
      - ./:/build

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: actix
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - ./docker-data/initdb/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data

  # image_storage:
  #   image: minimalcompact/thumbor
  #   environment:
  #     THUMBOR_NUM_PROCESSES: 4

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db-data:
