version: "3.7"
services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    tty: true # if not build app.
    environment:
      RUST_BACKTRACE: full
    ports: 
      - "3000:3000"
